title: David Zhang
email: davzee@hotmail.com
url: https://www.davzhang.me/
description: "Personal Website of David Zhang, Software Engineering Student at the University of Waterloo"

color:
  primary-dark: '#191919'

footer: David Zhang

social:
  - title: github
    url: https://github.com/davidozhang
  - title: linkedin
    url: https://linkedin.com/in/davzhang1
  - title: facebook
    url: https://www.facebook.com/davido.zhang
  - title: flickr
    url: https://flickr.com/photos/davzee

markdown: kramdown
permalink: pretty
